# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout and Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Run Deploy
      run: |
        cd rpicasesystem
        dotnet publish -c Release -o ../dotnet-app --runtime linux-arm --self-contained true
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: application-artifacts
        path: dotnet-app/

